BYBIT_API_KEY = 'YOUR-BYBIT-API-KEY'
BYBIT_SECRET_KEY = 'YOUR-BYBIT-SECRECT-KEY'

BINANCE_API_KEY='YOUR-BINANCE-API-KEY'
BINANCE_SECRET_KEY='YOUR-BINANCE-SECRECT-KEY'


timeframes=['1w','1d','4h','1h']
limit=200
symbols=[
	"BTC/USDT",
	"ETH/USDT",
	"BNB/USDT"
]